# Rustfmt configuration for waspy
# See https://rust-lang.github.io/rustfmt/ for all options
# Only using stable features (nightly features commented out)

edition = "2021"

# Maximum line width
max_width = 100

# Use Unix line endings
newline_style = "Unix"

# Reorder imports
reorder_imports = true

# Reorder modules
reorder_modules = true

# Use field init shorthand
use_field_init_shorthand = true

# Use try shorthand
use_try_shorthand = true

# Chain formatting
chain_width = 60

# Nightly-only features (uncomment if using nightly toolchain):
# format_strings = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# format_code_in_doc_comments = true
# normalize_comments = true
# wrap_comments = true
# comment_width = 80
